In [1]:
def main():
    print("Hello, World!")

if __name__ == "__main__":
    main()


Hello, World!


In [1]:
print("ram")

ram


In [2]:
from sklearn.preprocessing import OneHotEncoder
import numpy

In [3]:
from sklearn.preprocessing import OneHotEncoder
import numpy

In [9]:
a=10
print(a)

10


In [6]:
senence=["i love irpe", "Pritwi live irpe", "avinaba and prithwi is bad boy"]
a=[]
for ele in senence:
    p_= ele.lower().split()
    for ee in p_:
        a.append(ee)

print(a)    

['i', 'love', 'irpe', 'pritwi', 'live', 'irpe', 'avinaba', 'and', 'prithwi', 'is', 'bad', 'boy']


In [1]:
from sklearn.preprocessing.text import OneHotEncoder

encoder = OneHotEncoder(sparse=False)

data = [['Red'], ['Blue'], ['Green']]
encoded = encoder.fit_transform(data)

print(encoded)

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'

In [2]:
aaa= list(set(a))
print(aaa)

['pritwi', 'love', 'avinaba', 'i', 'live', 'irpe', 'prithwi', 'and', 'bad', 'boy', 'is']


In [8]:
from sklearn.preprocessing import OneHotEncoder
encoder= OneHotEncoder(sparse_output=False)

In [33]:
encoder.fit([aaa])

OneHotEncoder(sparse_output=False)

In [23]:
print("vocab", encoder.categories_[3])

vocab ['i']


In [19]:
for ele in senence:
    print(encoder.transform(ele))


ValueError: Expected 2D array, got scalar array instead:
array=i love irpe.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [24]:
from sklearn.feature_extraction.text import CountVectorizer

In [25]:
doc=["  i am a boy , i study in class 1sdwdw, he is  ram"]

In [26]:
ss=CountVectorizer()

In [30]:
w=ss.fit_transform(doc)

In [31]:
print(w.toarray())

[[1 1 1 1 1 1 1 1 1]]


In [44]:
from sklearn.feature_extraction.text import CountVectorizer
a= ["i am ram", "prithwi is ram", "i hate prithwi"]

ss1=CountVectorizer()

val=ss1.fit_transform(a)
   
print(val.toarray())

[[1 0 0 0 1]
 [0 0 1 1 1]
 [0 1 0 1 0]]


In [47]:
v= ss1.transform(a)
v.toarray()

array([[1, 0, 0, 0, 1],
       [0, 0, 1, 1, 1],
       [0, 1, 0, 1, 0]], dtype=int64)

In [50]:
ss1.get_feature_names_out()

array(['am', 'hate', 'is', 'prithwi', 'ram'], dtype=object)

In [53]:
from sklearn.feature_extraction.text import TfidfVectorizer

pp=TfidfVectorizer()
doc2=["prithwi is good", "ram is good", "sourav plays cricket"]
f_val=pp.fit_transform(doc2)
print(f_val.toarray())
pp.get_feature_names_out()

[[0.         0.51785612 0.51785612 0.         0.68091856 0.
  0.        ]
 [0.         0.51785612 0.51785612 0.         0.         0.68091856
  0.        ]
 [0.57735027 0.         0.         0.57735027 0.         0.
  0.57735027]]


array(['cricket', 'good', 'is', 'plays', 'prithwi', 'ram', 'sourav'],
      dtype=object)

In [2]:
# ===== ONE-HOT ENCODING COMPLETE GUIDE =====

# Example 1: Basic One-Hot Encoding with Colors
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import numpy as np

print("=" * 50)
print("EXAMPLE 1: Basic Color Encoding")
print("=" * 50)

colors_data = [['Red'], ['Blue'], ['Green'], ['Red'], ['Blue']]
encoder = OneHotEncoder(sparse_output=False)
encoded_colors = encoder.fit_transform(colors_data)

print("Original colors:", [c[0] for c in colors_data])
print("Category names:", encoder.categories_[0])
print("One-Hot Encoded:\n", encoded_colors)
df = pd.DataFrame(encoded_colors, columns=encoder.categories_[0])
print("As DataFrame:\n", df)

EXAMPLE 1: Basic Color Encoding
Original colors: ['Red', 'Blue', 'Green', 'Red', 'Blue']
Category names: ['Blue' 'Green' 'Red']
One-Hot Encoded:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
As DataFrame:
    Blue  Green  Red
0   0.0    0.0  1.0
1   1.0    0.0  0.0
2   0.0    1.0  0.0
3   0.0    0.0  1.0
4   1.0    0.0  0.0


In [7]:
from sklearn.preprocessing import OneHotEncoder
text =["i love irpe", "Pritwi live irpe", "avinaba and prithwi is"]
encoder = OneHotEncoder(sparse_output=False)

In [14]:
list_ = []
for ele in text:
    ele1=ele.lower().split()
    for ee in ele1:
        print(ee)
        list_.append(ee)


i
love
irpe
pritwi
live
irpe
avinaba
and
prithwi
is


In [15]:
print(list_)

['i', 'love', 'irpe', 'pritwi', 'live', 'irpe', 'avinaba', 'and', 'prithwi', 'is']


In [17]:
encoded_ = encoder.fit_transform([list_])

In [23]:
print("One-Hot Encoded:\n", encoded_)


One-Hot Encoded:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [25]:
# ===== ONE-HOT ENCODING WITH TEXT =====
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import numpy as np

# Your text data
text = ["prithwi is good", "i am bad", "prithwi is bad"]

# Step 1: Extract all unique words
all_words = []
for sentence in text:
    words = sentence.lower().split()
    all_words.extend(words)

unique_words = list(set(all_words))
print("Unique words:", sorted(unique_words))

# Step 2: Convert text to word vectors (list of words for each sentence)
text_vectors = []
for sentence in text:
    words = sentence.lower().split()
    text_vectors.append(words)

# Step 3: Create and fit OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)

# Prepare data: each word as a separate row
encoded_data = []
for words in text_vectors:
    for word in words:
        encoded_data.append([word])

# Fit and transform
encoded = encoder.fit_transform(encoded_data)

print("\n" + "="*50)
print("ONE-HOT ENCODING OUTPUT")
print("="*50)
print("\nOriginal text:")
for i, t in enumerate(text):
    print(f"  {i+1}. {t}")

print("\nWord categories:", encoder.categories_[0])

print("\nEncoded shape:", encoded.shape)
print("\nEncoded matrix (each row = one word):")
print(encoded)

# Create DataFrame
df_encoded = pd.DataFrame(encoded, 
                          columns=encoder.categories_[0])
print("\nAs DataFrame:")
print(df_encoded)

print("\nExplanation:")
print("- Each row = one word")
print("- Each column = one unique word category")
print("- 1 = this is the word")
print("- 0 = this is not the word")

Unique words: ['am', 'bad', 'good', 'i', 'is', 'prithwi']

ONE-HOT ENCODING OUTPUT

Original text:
  1. prithwi is good
  2. i am bad
  3. prithwi is bad

Word categories: ['am' 'bad' 'good' 'i' 'is' 'prithwi']

Encoded shape: (9, 6)

Encoded matrix (each row = one word):
[[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]]

As DataFrame:
    am  bad  good    i   is  prithwi
0  0.0  0.0   0.0  0.0  0.0      1.0
1  0.0  0.0   0.0  0.0  1.0      0.0
2  0.0  0.0   1.0  0.0  0.0      0.0
3  0.0  0.0   0.0  1.0  0.0      0.0
4  1.0  0.0   0.0  0.0  0.0      0.0
5  0.0  1.0   0.0  0.0  0.0      0.0
6  0.0  0.0   0.0  0.0  0.0      1.0
7  0.0  0.0   0.0  0.0  1.0      0.0
8  0.0  1.0   0.0  0.0  0.0      0.0

Explanation:
- Each row = one word
- Each column = one unique word category
- 1 = this is the word
- 0 = this is not the word
